# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_calculus', '0002_auto_20160207_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(default='aaaa', max_length=200),
        ),
    ]
