# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_calculus', '0003_document_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='output')),
                ('filename', models.CharField(default='aaaa', max_length=200)),
            ],
        ),
    ]
