# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_calculus', '0004_documentoutput'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoutput',
            name='textfield',
            field=models.TextField(default=''),
        ),
    ]
