# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_calculus', '0005_documentoutput_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoutput',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
